#ifndef MOTORSCONTROLL_ARM_GLOBAL_H
#define MOTORSCONTROLL_ARM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOTORSCONTROLL_ARM_LIBRARY)
#  define MOTORSCONTROLL_ARMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MOTORSCONTROLL_ARMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MOTORSCONTROLL_ARM_GLOBAL_H
