#ifndef MOTORSCONTROLLER_ARM_GLOBAL_H
#define MOTORSCONTROLLER_ARM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOTORSCONTROLLER_ARM_LIBRARY)
#  define MOTORSCONTROLLER_ARMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MOTORSCONTROLLER_ARMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MOTORSCONTROLLER_ARM_GLOBAL_H
